name: Generate Snake

on:
  schedule: # har din raat 12 baje run karega
    - cron: "0 0 * * *"
  workflow_dispatch: # manually bhi run kar sakta hai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: svpcet-code
          outputs: dist/snake.svg

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
